name: Send request to rebuild dag image
on:
  push:
    paths:
      - 'dags/**'

env:
   USER: AireeApp1
   WORKFLOW_ID: build_image_worker.yaml

jobs:
  trigger_rebuild_dag_image:
    runs-on: azure
    steps:
    - name: Define repo path
      run: echo "GIT_REPO=$(echo ${GITHUB_REPOSITORY} | sed -e 's/workspace_data_dev/app_dev/g')" >> $GITHUB_ENV
    - name: trigger dag API
      run: |
         curl -X POST -u ${USER}:${PAT_TOKEN} \
         -H "Accept: application/vnd.github.v3+json" \
         --url https://api.github.com/repos/${GIT_REPO}/actions/workflows/${WORKFLOW_ID}/dispatches \
         -d '{"ref":"main"}'
