name: Send request to rebuild dag image
on:
  push:
    paths:
      - 'dags/**'

env:
   WORKFLOW_ID: build_image_worker.yaml

jobs:
  trigger_rebuild_dag_image:
    runs-on: [self-hosted,{{cookiecutter.labels}}]
    steps:
    - name: Define repo path
      run: echo "GIT_REPO=$(echo ${GITHUB_REPOSITORY} | sed -e 's/workspace_data_{{cookiecutter.env}}/app_{{cookiecutter.env}}/g')" >> $GITHUB_ENV
    - name: trigger dag API
      run: |
         curl -X POST \
         -H "Authorization: token {% raw %}${{ secrets.TF_VAR_github_token }}{% endraw %}" \
         --url https://api.github.com/repos/${GIT_REPO}/actions/workflows/${WORKFLOW_ID}/dispatches \
         -d '{"ref":"main"}'
